server:
  port: 9024

spring:
  application:
    name: DEPARTMENT-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#application:
profiles:
  - dev
  - test
  - prod
  - 1
  - 2

hashMap:
  raghu:  20
  shashi: 21
  setty:  25

applicationTest : applicationTest
